### ISSUE TITLE
Serializing from `serde_json::Value` changes if `arbitrary_precision` feature is enabled

### ISSUE THREAD

**Issue by nicoan-ft** [zenlist/serde_dynamo#90]
Hello! I've noticed this strange behaviour when the feature `arbitrary_precision` from `serde_json` is enabled. This is the current code I have:

```rust
use serde_dynamo::AttributeValue;
use std::collections::HashMap;

use serde::Serialize;

#[derive(Debug, Serialize)]
pub struct D {
    d: u64,
}

fn main() {
    let test = D { d: 42 };

    let test_json = serde_json::to_value(test).unwrap();
    println!("JSON Value:\n {test_json:#?}");

    let item_json: HashMap<String, AttributeValue> = serde_dynamo::to_item(&test_json).unwrap();
    println!("JSON ITEM:\n{item_json:#?}");
}
```

with the following `Cargo.toml`:
```toml
[package]
name = "serde_dynamo_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0" , features = ["derive"] }
serde_dynamo = { version = "4.2.9" }
serde_json = { version = "1.0.108" }
#serde_json = { version = "1.0.108",  features = ["arbitrary_precision"] }
```

The output is this:
```
JSON Value:
 Object {
    "d": Number(42),
}
JSON ITEM:
{
    "d": N(
        "42",
    ),
}
```

but when I enable the  `serde_json`'s `arbitrary_precision` feature, the output changes to this:
```
JSON Value:
 Object {
    "d": Number(42),
}
JSON ITEM:
{
    "d": M(
        {
            "$serde_json::private::Number": S(
                "42",
            ),
        },
    ),
}
```

Thank you!
